export const words = [
	"Bisasam", 
	"Bisaknosp",
	"Bisaflor",
	"Glumanda",
	"Glutexo",
	"Glurak",
	"Schiggy",
	"Schillok",
	"Turtok",
	"Raupy",
	"Safcon",
	"Smettbo",
	"Hornliu",
	"Kokuna",
	"Bibor",
	"Taubsi",
	"Tauboga",
	"Tauboss",
	"Rattfratz",
	"Rattikarl",
	"Habitak",
	"Ibitak",
	"Rettan",
	"Arbok",
	"Pikachu",
	"Raichu",
	"Sandan",
	"Sandamer",
	"Nidoran",
	"Nidorina",
	"Nidoqueen",
	"Nidorino",
	"Nidoking",
	"Piepi",
	"Pixi",
	"Vulpix",
	"Vulnona",
	"Pummeluff",
	"Knuddeluff",
	"Zubat",
	"Golbat",
	"Myrapla",
	"Duflor",
	"Giflor",
	"Paras",
	"Parasek",
	"Bluzuk",
	"Digda",
	"Digdri",
	"Mauzi",
	"Snobilikat",
	"Enton",
	"Entoron",
	"Menki",
	"Rasaff",
	"Fukano",
	"Arkani",
	"Quapsel",
	"Quapuzi",
	"Quappo",
	"Abra",
	"Kadabra",
	"Simsala",
	"Machollo",
	"Maschock",
	"Machomei",
	"Knofensa",
	"Ultrigaria",
	"Sarzenia",
	"Tentacha",
	"Tentoxa",
	"Kleinstein",
	"Georock",
	"Geowaz",
	"Ponita",
	"Galoppa",
	"Flegmon",
	"Lahmus",
	"Magnetilo",
	"Magneton",
	"Porenta",
	"Dodu",
	"Dodri",
	"Jurob",
	"Jugong",
	"Sleima",
	"Sleimok",
	"Muschas",
	"Austos",
	"Nebulak",
	"Alpollo",
	"Gengar",
	"Onix",
	"Traumato",
	"Hypno",
	"Krabby",
	"Kingler",
	"Voltoball",
	"Lektroball",
	"Owei",
	"Kokowei",
	"Tragosso",
	"Knogga",
	"Kicklee",
	"Nokchan",
	"Schlurp",
	"smoggon",
	"smogmog",
	"Rihorn",
	"Rizeros",
	"Chaneira",
	"Tangela",
	"Kangama",
	"Seeper",
	"Seemon",
	"Goldini",
	"Golking",
	"Sterndu",
	"Starmie",
	"Pantimos",
	"Sichlor",
	"Rossana",
	"Elektek",
	"Magmar",
	"Pinsir",
	"Tauros",
	"Kapador",
	"Garados",
	"Lapras",
	"Ditto",
	"Evoli",
	"Aquana",
	"Blitza",
	"Flamara",
	"Porygon",
	"Amonitas",
	"Amoroso",
	"Kabuto",
	"Kabutops",
	"Aerodactyl",
	"Relaxo",
	"Arktos",
	"Zapdos",
	"Lavados",
	"Dratini",
	"Dragonir",
	"Dragoran",
	"Mewtwo",
	"Mew",
	"Endivie",
	"Lorblatt",
	"Meganie",
	"Feurigel",
	"Igelavar",
	"Tornupto",
	"Karnimani",
	"Tyracroc",
	"Impergator",
	"Wiesor",
	"Wiesenior",
	"Hoothoot",
	"Noctuh",
	"Ledyba",
	"Ledian",
	"Webarak",
	"Ariados",
	"Iksbat",
	"Lampi",
	"Lanturn",
	"Pichu",
	"Pii",
	"Fluffeluff",
	"Togepi",
	"Togetic",
	"Natu",
	"Xatu",
	"Voltilamm",
	"Waaty",
	"Ampharos",
	"Blubella",
	"Marill",
	"Azumarill",
	"Mogelbaum",
	"Quaxo",
	"Hoppspross",
	"Hubelupf",
	"Papungha",
	"Griffel",
	"Sonnkern",
	"Sonnflora",
	"Yanma",
	"Feelino",
	"Morlord",
	"Psiana",
	"Nachtara",
	"Kramurx",
	"Laschoking",
	"Traunfugil",
	"Incognito",
	"Woingenau",
	"Girafarig",
	"Tanza",
	"Forstellka",
	"Dummisel",
	"Skorgla",
	"Stahlos",
	"Snubbull",
	"Granbull",
	"Baldorfish",
	"Scherox",
	"Pottrot",
	"Skaraborn",
	"Sniebel",
	"Teddiursa",
	"Ursaring",
	"Schneckmag",
	"Magcargo",
	"Quikel",
	"Keifel",
	"Corasonn",
	"Remoraid",
	"Octillery",
	"Botogel",
	"Mantax",
	"Panzaeron",
	"Hunduster",
	"Hundemon",
	"Seedraking",
	"Phanpy",
	"Donphan",
	"Porygon2",
	"Damhirplex",
	"Farbeagle",
	"Rabauz",
	"Kapoera",
	"Kussilla",
	"Elekid",
	"Magby",
	"Miltank",
	"Heiteira",
	"Raikou",
	"Entei",
	"Suicune",
	"Larvitar",
	"Pupitar",
	"Despotar",
	"Lugia",
	"Ho-Oh",
	"Celebi",
	"Geckabor",
	"Reptain",
	"Gewaldro",
	"Flemmli",
	"Jungglut",
	"Lohgock",
	"Hydropi",
	"Moorabbel",
	"Sumpex",
	"Fiffyen",
	"Magnayen",
	"Zigzachs",
	"Geradachs",
	"Waumpel",
	"Schaloko",
	"Papinella",
	"Panekon",
	"Pudox",
	"Loturzel",
	"Lombrero",
	"Kapalores",
	"Samurzel",
	"Blanas",
	"Tengulist",
	"Schwalbini",
	"Swalboss",
	"Wingull",
	"Pelipper",
	"Trasla",
	"Kirlia",
	"Guardevoir",
	"Gehweiher",
	"Maskeregen",
	"Shroomish",
	"Kapilz",
	"Bummelz",
	"Muntier",
	"Letarking",
	"Nincada",
	"Ninjask",
	"Ninjatom",
	"Flurmel",
	"Krakelo",
	"Krawumms",
	"Makuhita",
	"Hariyama",
	"Azurill",
	"Nasgnet",
	"Eneco",
	"Enekoro",
	"Zobiris",
	"Flunkifer",
	"Stollunior",
	"Stollrak",
	"Stollos",
	"Meditite",
	"Meditalis",
	"Frizelbliz",
	"Voltenso",
	"Plusle",
	"Minun",
	"Volbeat",
	"Illumise",
	"Roselia",
	"schluppuk",
	"schluckwech",
	"Kanivanha",
	"Tohaido",
	"Wailmer",
	"Wailord",
	"Camaub",
	"Camerupt",
	"Qurtel",
	"Spoink",
	"Groink",
	"Pandir",
	"Knacklion",
	"Vibrava",
	"Libelldra",
	"Tuska",
	"Noktuska",
	"Wablu",
	"Altaria",
	"Sengo",
	"Vipitis",
	"Lunastein",
	"Sonnfel",
	"Schmerbe",
	"Welsar",
	"Krebscorps",
	"Krebutak",
	"puppance",
	"Lepumentas",
	"Liliep",
	"Wielie",
	"Anorith",
	"Armaldo",
	"Barschwa",
	"Milotic",
	"Formeo",
	"Kecleon",
	"Shuppet",
	"Banette",
	"Zwirrlicht",
	"Zwirrklops",
	"Tropius",
	"Palimpalim",
	"Absol",
	"Isso",
	"Schneppke",
	"Firnontor",
	"Seemops",
	"Seejong",
	"Walraisa",
	"Perlu",
	"Alabyss",
	"Saganabyss",
	"Relicanth",
	"Liebiskus",
	"Kindwurm",
	"Draschel",
	"Brutalanda",
	"Tanhel",
	"Metang",
	"Metagross",
	"Regirock",
	"Regice",
	"Registeel",
	"Latias",
	"Latios",
	"Kyogre",
	"Groudon",
	"Rayquaza",
	"Jirachi",
	"Deoxys",
	"Chelast",
	"Chelcarain",
	"Chelterrar",
	"Panflam",
	"Panpyro",
	"Panferno",
	"Plinfa",
	"Pliprin",
	"Impoleon",
	"Staralili",
	"Staravia",
	"Staraptor",
	"Bidiza",
	"Bidifass",
	"Zirpurze",
	"Zirpeise",
	"Sheinux",
	"Luxio",
	"Luxtra",
	"Knospi",
	"Roserade",
	"Kognodon",
	"Rameidon",
	"Schilterus",
	"Bollteruns",
	"Burmy",
	"Burmadame",
	"Moterpel",
	"Wadribie",
	"Honweisel",
	"Pachirisu",
	"Bamelin",
	"Bojelin",
	"Kigugi",
	"Kinoso",
	"Shallelos",
	"Gastrodon",
	"Ambipom",
	"Driftlon",
	"Drifzepelin",
	"Haspiror",
	"Schlapohr",
	"Traunmagil",
	"Kramshef",
	"Charmian",
	"Shnurgarst",
	"Klingplim",
	"Stunkapuh",
	"Skuntank",
	"Bronzel",
	"Bronzong",
	"Mobai",
	"Pantimimi",
	"Wonneira",
	"Plaudagei",
	"Krypuk",
	"Kaumalat",
	"Kanrksel",
	"Knackrack",
	"Mampfaxo",
	"Riolu",
	"Lucario",
	"Hippopotas",
	"Hippotamus",
	"Pionskora",
	"Piondragi",
	"Glibunkel",
	"Toxiquak",
	"Venuflibis",
	"Finneon",
	"Lumineon",
	"Mantirps",
	"Scneebedeck",
	"Rexblisar",
	"Snibunna",
	"Magnezone",
	"Schlurplek",
	"Rihornior",
	"Tangoloss",
	"Elevoltek",
	"Magbrandt",
	"Togekiss",
	"Yanmega",
	"Folipurba",
	"Glaziola",
	"Skorgro",
	"Mamutel",
	"Porygon-Z",
	"Gallagladi",
	"Voluminas",
	"Zwirrfinst",
	"Frosdedje",
	"Rotom",
	"Selfe",
	"Vesprit",
	"Tobutz",
	"Dialga",
	"Palkia",
	"Heatran",
	"Regigigas",
	"Giratina",
	"Cresselia",
	"Phione",
	"Manaphy",
	"Darkrai",
	"Shaymin",
	"Arceus",
	"Victini",
	
	// # "Snivy",
	// # "Servine",
	// # "Serperior",
	// # "Tepig",
	// # "Pignite",
	// # "Emboar",
	// # "Oshawott",
	// # "Dewott",
	// # "Samurott",
	// # "Patrat",
	// # "Watchog",
	// # "Lillipup",
	// # "Herdier",
	// # "Stoutland",
	// # "Purrloin",
	// # "Liepard",
	// # "Pansage",
	// # "Simisage",
	// # "Pansear",
	// # "Simisear",
	// # "Panpour",
	// # "Simipour",
	// # "Munna",
	// # "Musharna",
	// # "Pidove",
	// # "Tranquill",
	// # "Unfezant",
	// # "Blitzle",
	// # "Zebstrika",
	// # "Roggenrola",
	// # "Boldore",
	// # "Gigalith",
	// # "Woobat",
	// # "Swoobat",
	// # "Drilbur",
	// # "Excadrill",
	// # "Audino",
	// # "Timburr",
	// # "Gurdurr",
	// # "Conkeldurr",
	// # "Tympole",
	// # "Palpitoad",
	// # "Seismitoad",
	// # "Throh",
	// # "Sawk",
	// # "Sewaddle",
	// # "Swadloon",
	// # "Leavanny",
	// # "Venipede",
	// # "Whirlipede",
	// # "Scolipede",
	// # "Cottonee",
	// # "Whimsicott",
	// # "Petilil",
	// # "Lilligant",
	// # "Basculin",
	// # "Sandile",
	// # "Krokorok",
	// # "Krookodile",
	// # "Darumaka",
	// # "Darmanitan",
	// # "Maractus",
	// # "Dwebble",
	// # "Crustle",
	// # "Scraggy",
	// # "Scrafty",
	// # "Sigilyph",
	// # "Yamask",
	// # "Cofagrigus",
	// # "Tirtouga",
	// # "Carracosta",
	// # "Archen",
	// # "Archeops",
	// # "Trubbish",
	// # "Garbodor",
	// # "Zorua",
	// # "Zoroark",
	// # "Minccino",
	// # "Cinccino",
	// # "Gothita",
	// # "Gothorita",
	// # "Gothitelle",
	// # "Solosis",
	// # "Duosion",
	// # "Reuniclus",
	// # "Ducklett",
	// # "Swanna",
	// # "Vanillite",
	// # "Vanillish",
	// # "Vanilluxe",
	// # "Deerling",
	// # "Sawsbuck",
	// # "Emolga",
	// # "Karrablast",
	// # "Escavalier",
	// # "Foongus",
	// # "Amoonguss",
	// # "Frillish",
	// # "Jellicent",
	// # "Alomomola",
	// # "Joltik",
	// # "Galvantula",
	// # "Ferroseed",
	// # "Ferrothorn",
	// # "Klink",
	// # "Klang",
	// # "Klinklang",
	// # "Tynamo",
	// # "Eelektrik",
	// # "Eelektross",
	// # "Elgyem",
	// # "Beheeyem",
	// # "Litwick",
	// # "Lampent",
	// # "Chandelure",
	// # "Axew",
	// # "Fraxure",
	// # "Haxorus",
	// # "Cubchoo",
	// # "Beartic",
	// # "Cryogonal",
	// # "Shelmet",
	// # "Accelgor",
	// # "Stunfisk",
	// # "Mienfoo",
	// # "Mienshao",
	// # "Druddigon",
	// # "Golett",
	// # "Golurk",
	// # "Pawniard",
	// # "Bisharp",
	// # "Bouffalant",
	// # "Rufflet",
	// # "Braviary",
	// # "Vullaby",
	// # "Mandibuzz",
	// # "Heatmor",
	// # "Durant",
	// # "Deino",
	// # "Zweilous",
	// # "Hydreigon",
	// # "Larvesta",
	// # "Volcarona",
	// # "Cobalion",
	// # "Terrakion",
	// # "Virizion",
	// # "Tornadus",
	// # "Thundurus",
	// # "Reshiram",
	// # "Zekrom",
	// # "Landorus",
	// # "Kyurem",
	// # "Keldeo",
	// # "Meloetta",
	// # "Genesect",
	// # "Chespin",
	// # "Quilladin",
	// # "Chesnaught",
	// # "Fennekin",
	// # "Braixen",
	// # "Delphox",
	// # "Froakie",
	// # "Frogadier",
	// # "Greninja",
	// # "Bunnelby",
	// # "Diggersby",
	// # "Fletchling",
	// # "Fletchinder",
	// # "Talonflame",
	// # "Scatterbug",
	// # "Spewpa",
	// # "Vivillon",
	// # "Litleo",
	// # "Pyroar",
	// # "Flabebe",
	// # "Floette",
	// # "Florges",
	// # "Skiddo",
	// # "Gogoat",
	// # "Pancham",
	// # "Pangoro",
	// # "Furfrou",
	// # "Espurr",
	// # "Meowstic",
	// # "Honedge",
	// # "Doublade",
	// # "Aegislash",
	// # "Spritzee",
	// # "Aromatisse",
	// # "Swirlix",
	// # "Slurpuff",
	// # "Inkay",
	// # "Malamar",
	// # "Binacle",
	// # "Barbaracle",
	// # "Skrelp",
	// # "Dragalge",
	// # "Clauncher",
	// # "Clawitzer",
	// # "Helioptile",
	// # "Heliolisk",
	// # "Tyrunt",
	// # "Tyrantrum",
	// # "Amaura",
	// # "Aurorus",
	// # "Sylveon",
	// # "Hawlucha",
	// # "Dedenne",
	// # "Carbink",
	// # "Goomy",
	// # "Sliggoo",
	// # "Goodra",
	// # "Klefki",
	// # "Phantump",
	// # "Trevenant",
	// # "Pumpkaboo",
	// # "Gourgeist",
	// # "Bergmite",
	// # "Avalugg",
	// # "Noibat",
	// # "Noivern",
	// # "Xerneas",
	// # "Yveltal",
	// # "Zygarde",
	// # "Diancie",
	// # "Hoopa",
	// # "Volcanion",
	// # "Rowlet",
	// # "Dartrix",
	// # "Decidueye",
	// # "Litten",
	// # "Torracat",
	// # "Incineroar",
	// # "Popplio",
	// # "Brionne",
	// # "Primarina",
	// # "Pikipek",
	// # "Trumbeak",
	// # "Toucannon",
	// # "Yungoos",
	// # "Gumshoos",
	// # "Grubbin",
	// # "Charjabug",
	// # "Vikavolt",
	// # "Crabrawler",
	// # "Crabominable",
	// # "Oricorio",
	// # "Cutiefly",
	// # "Ribombee",
	// # "Rockruff",
	// # "Lycanroc",
	// # "Wishiwashi",
	// # "Mareanie",
	// # "Toxapex",
	// # "Mudbray",
	// # "Mudsdale",
	// # "Dewpider",
	// # "Araquanid",
	// # "Fomantis",
	// # "Lurantis",
	// # "Morelull",
	// # "Shiinotic",
	// # "Salandit",
	// # "Salazzle",
	// # "Stufful",
	// # "Bewear",
	// # "Bounsweet",
	// # "Steenee",
	// # "Tsareena",
	// # "Comfey",
	// # "Oranguru",
	// # "Passimian",
	// # "Wimpod",
	// # "Golisopod",
	// # "Sandygast",
	// # "Palossand",
	// # "Pyukumuku",
	// # "Type: Null",
	// # "Silvally",
	// # "Minior",
	// # "Komala",
	// # "Turtonator",
	// # "Togedemaru",
	// # "Mimikyu",
	// # "Bruxish",
	// # "Drampa",
	// # "Dhelmise",
	// # "Jangmo-o",
	// # "Hakamo-o",
	// # "Kommo-o",
	// # "Tapu Koko",
	// # "Tapu Lele",
	// # "Tapu Bulu",
	// # "Tapu Fini",
	// # "Cosmog",
	// # "Cosmoem",
	// # "Solgaleo",
	// # "Lunala",
	// # "Nihilego",
	// # "Buzzwole",
	// # "Pheromosa",
	// # "Xurkitree",
	// # "Celesteela",
	// # "Kartana",
	// # "Guzzlord",
	// # "Necrozma",
	// # "Magearna",
	// # "Marshadow",
	// # "Poipole",
	// # "Naganadel",
	// # "Stakataka",
	// # "Blacephalon",
	// # "Zeraora",
	// # "Meltan",
	// # "Melmetal",
	// # "Grookey",
	// # "Thwackey",
	// # "Rillaboom",
	// # "Scorbunny",
	// # "Raboot",
	// # "Cinderace",
	// # "Sobble",
	// # "Drizzile",
	// # "Inteleon",
	// # "Skwovet",
	// # "Greedent",
	// # "Rookidee",
	// # "Corvisquire",
	// # "Corviknight",
	// # "Blipbug",
	// # "Dottler",
	// # "Orbeetle",
	// # "Nickit",
	// # "Thievul",
	// # "Gossifleur",
	// # "Eldegoss",
	// # "Wooloo",
	// # "Dubwool",
	// # "Chewtle",
	// # "Drednaw",
	// # "Yamper",
	// # "Boltund",
	// # "Rolycoly",
	// # "Carkol",
	// # "Coalossal",
	// # "Applin",
	// # "Flapple",
	// # "Appletun",
	// # "Silicobra",
	// # "Sandaconda",
	// # "Cramorant",
	// # "Arrokuda",
	// # "Barraskewda",
	// # "Toxel",
	// # "Toxtricity",
	// # "Sizzlipede",
	// # "Centiskorch",
	// # "Clobbopus",
	// # "Grapploct",
	// # "Sinistea",
	// # "Polteageist",
	// # "Hatenna",
	// # "Hattrem",
	// # "Hatterene",
	// # "Impidimp",
	// # "Morgrem",
	// # "Grimmsnarl",
	// # "Obstagoon",
	// # "Perrserker",
	// # "Cursola",
	// # "Sirfetch'd",
	// # "Mr. Rime",
	// # "Runerigus",
	// # "Milcery",
	// # "Alcremie",
	// # "Falinks",
	// # "Pincurchin",
	// # "Snom",
	// # "Frosmoth",
	// # "Stonjourner",
	// # "Eiscue",
	// # "Indeedee",
	// # "Morpeko",
	// # "Cufant",
	// # "Copperajah",
	// # "Dracozolt",
	// # "Arctozolt",
	// # "Dracovish",
	// # "Arctovish",
	// # "Duraludon",
	// # "Dreepy",
	// # "Drakloak",
	// # "Dragapult",
	// # "Zacian",
	// # "Zamazenta",
	// # "Eternatus",
	// # "Kubfu",
	// # "Urshifu",
	// # "Zarude",
	// # "Regieleki",
	// # "Regidrago",
	// # "Glastrier",
	// # "Spectrier",
	// # "Calyrex",
	// # "Wyrdeer",
	// # "Kleavor",
	// # "Ursaluna",
	// # "Basculegion",
	// # "Sneasler",
	// # "Overqwil",
	// # "Enamorus"
];