# normal = [
#     "Rattfratz",
#     "Rattikarl",
#     "Pummeluff",
#     "Knuddeluff",
#     "Mauzi",
#     "Snobilikat",
#     "Schlurp",
#     "Chaneira",
#     "Tauros",
#     "Ditto",
#     "Evoli",
#     "Porygon",
#     "Relaxo",
#     "Wiesor",
#     "Wiesenior",
#     "Fluffeluff",
#     "Griffel",
#     "Girafarig",
#     "Dummisel",
#     "Teddiursa",
#     "Ursaring",
#     "Porygon2",
#     "Damhirplex",
#     "Farbeagle",
#     "Miltank",
#     "Heiteira",
#     "Kangama",
#     "Zigzachs",
#     "Geradaks",
#     "Bummelz",
#     "Muntier",
#     "Letarking",
#     "Flurmel",
#     "Krakeelo",
#     "Krawumms",
#     "Eneco",
#     "Enekoro",
#     "Pandir",
#     "Sengo",
#     "Formeo",
#     "Kecleon",
#     "Bidiza",
#     "Ambidiffel",
#     "Haspiror",
#     "Schlapor",
#     "Charmian",
#     "Shnurgarst",
#     "Wonneira",
#     "Mampfaxo",
#     "Schlurplek",
#     "Porygon-Z",
#     "Regigigas",
#     "Arceus",
#     "Azurill",
#     "Bidifass",
# ]

ground = [
    "Sandan",
    "Sandamer",
    "Digda",
    "Digdri",
    "Tragosso",
    "Knogga",
    "Phanpy",
    "Donphan",
    "Knacklion",
    "Groudon",
    "Hippopotas",
    "Hippoterus",
    "Vibrava",
    "Libelldra",
    "Skorgla",
    "Skorgro",
    "Rihorn",
    "Rizeros",
    "Rihornior",
    "Puppance",
    "Lepumentas",
]

# dragon = [
#     "Dratini",
#     "Dragonir",
#     "Kindwurm",
#     "Draschel",
#     "Kaumalat",
#     "Knarksel",
#     "Knackrack",
#     "Dragoran",
#     "Altaria",
#     "Brutalanda",
#     "Rayquaza",
#     "Latias",
#     "Latios",
# ]

# ice = [
#     "Schneppke",
#     "Firnontor",
#     "Regice",
#     "Glaziola",
#     "Quikel",
#     "Keifel",
#     "Mamutel",
#     "Arktos",
#     "Botogel",
#     "Frosdedje",
#     "Rossana",
#     "Kussilla",
#     "Seemops",
#     "Seejong",
#     "Walraisa",
# ]

# elektrik = [
#     "Pikachu",
#     "Raichu",
#     "Voltobal",
#     "Lektrobal",
#     "Elektek",
#     "Blitza",
#     "Pichu",
#     "Voltilamm",
#     "Waaty",
#     "Ampharos",
#     "Elekid",
#     "Raikou",
#     "Frizelbliz",
#     "Voltenso",
#     "Plusle",
#     "Minun",
#     "Sheinux",
#     "Luxio",
#     "Luxtra",
#     "Pachirisu",
#     "Elevoltek",
#     "Zapdos",
#     "Rotom",
#     "Magnetilo",
#     "Magneton",
#     "Magnezone",
# ]

# fairy = [
#     "Piepi",
#     "Pixi",
#     "Pii",
#     "Togepi",
#     "Snubbull",
#     "Granbull",
#     "Togetic",
#     "Togekiss",
# ]

# fire = [
#     "Glumanda",
#     "Glutexo",
#     "Vulpix",
#     "Vulnona",
#     "Fukano",
#     "Arkani",
#     "Ponita",
#     "Gallopa",
#     "Magmar",
#     "Flamara",
#     "Feurigel",
#     "Igelavar",
#     "Tornupto",
#     "Schneckmag",
#     "Magby",
#     "Entei",
#     "Flemmli",
#     "Qurtel",
#     "Panflam",
#     "Magbrant",
#     "Camaub",
#     "Camerupt",
#     "Glurak",
#     "Lavados",
#     "Ho-Oh",
#     "Magcargo",
#     "Jungglut",
#     "Lohgock",
#     "Panpyro",
#     "Panferno",
#     "Heatran",
# ]

# flying = [
#     "Taubsi",
#     "Tauboga",
#     "Tauboss",
#     "Habitak",
#     "Ibitak",
#     "Porenta",
#     "Dodu",
#     "Dodri",
#     "Hoothoot",
#     "Noctuh",
#     "Schwalbini",
#     "Schwalboss",
#     "Wablu",
#     "Staralili",
#     "Staravia",
#     "Staraptor",
#     "Plaudagei",
# ]

# ghost = [
#     "Traunfugil",
#     "Shuppet",
#     "Banette",
#     "Zwirrlicht",
#     "Zwirrklop",
#     "Traunmagil",
#     "Zwirrfinst",
#     "Giratina",
#     "Driftlon",
#     "Drifzepeli",
#     "Nebulak",
#     "Alpollo",
#     "Gengar",
#     "Kryppuk"
# ]

# rock = [
#     "Mogelbaum",
#     "Nasgnet",
#     "Regirock",
#     "Koknodon",
#     "Rameidon",
#     "Mobai",
#     "Kleinstein",
#     "Georok",
#     "Geowaz",
#     "Onix",
#     "Larvitar",
#     "Pupitar",
#     "Aerodactyl",
#     "Anorith",
#     "Armaldo",
#     "Liliep",
#     "Wielie",
#     "Lunastein",
#     "Sonnfel",
#     "Schilterus",
#     "Bollterus",
#     "Voluminas",
#     "Despotar",
#     "Amonitas",
#     "Amoroso",
#     "Kabuto",
#     "Kabutops",
# ]

# poison = [
#     "Rettan",
#     "Arbok",
#     "Nidoran",
#     "Nidorina",
#     "Nidorino",
#     "Sleima",
#     "Sleimok",
#     "Smogon",
#     "Smogmog",
#     "Schluppuck",
#     "Schlukwech",
#     "Vipitis",
#     "Nidoqueen",
#     "Nidoking",
#     "Zubat",
#     "Golbat",
#     "Iksbat",
#     "Pionskora",
#     "Glibunkel",
#     "Toxiquak",
#     "Skunkapuh",
#     "Skuntank",
#     "Piondragi",
# ]

# bug = [
#     "Raupy",
#     "Safcon",
#     "Pinsir",
#     "Tannza",
#     "Waumpel",
#     "Schaloko",
#     "Panekon",
#     "Volbeat",
#     "Illumise",
#     "Zirpurze",
#     "Zirpeise",
#     "Burmy",
#     "Nincada",
#     "Smettbo",
#     "Sichlor",
#     "Ledyba",
#     "Ledian",
#     "Yanma",
#     "Papinella",
#     "Maskeregen",
#     "Ninjask",
#     "Moterpel",
#     "Wadribie",
#     "Honweisel",
#     "Yanmega",
#     "Ninjatom",
#     "Pottrott",
#     "Hornliu",
#     "Kokuna",
#     "Bibor",
#     "Bluzuk",
#     "Omot",
#     "Webarak",
#     "Ariados",
#     "Pudox",
#     "Skaraborn",
#     "Paras",
#     "Parasek",
#     "Burmadame",
#     "Forstellka",
#     "Scherox",
#     "Gehweier",
# ]

# fighting = [
#     "Menki",
#     "Rasaff",
#     "Machollo",
#     "Maschock",
#     "Machomei",
#     "Kicklee",
#     "Nockchan",
#     "Rabauz",
#     "Kapoera",
#     "Makuhita",
#     "Hariyama",
#     "Riolu",
#     "Meditie",
#     "Meditalis",
#     "Lucario",
# ]

# grass = [
#     "Tangela",
#     "Endivie",
#     "Lorblatt",
#     "Meganie",
#     "Blubella",
#     "Sonnkern",
#     "Sonnflora",
#     "Geckabor",
#     "Reptain",
#     "Gewaldro",
#     "Samurzel",
#     "Knilz",
#     "Tuska",
#     "Chelast",
#     "Chelcarain",
#     "Kikugi",
#     "Kinoso",
#     "Venuflibis",
#     "Tangoloss",
#     "Folipurba",
#     "Shaymin",
#     "Chelterrar",
#     "Shnebedeck",
#     "Rexblisar",
#     "Hoppspross",
#     "Hubelupf",
#     "Papungha",
#     "Tropius",
#     "Bisasam",
#     "Bisaknosp",
#     "Bisaflor",
#     "Myrapla",
#     "Duflor",
#     "Giflor",
#     "Knofensa",
#     "Ultrigaria",
#     "Sarzenia",
#     "Roselia",
#     "Knospi",
#     "Roserade",
#     "Kapilz",
#     "Owei",
#     "Kokowei",
#     "Blanas",
#     "Tengulist",
#     "Noktuska",
# ]

# psychic = [
#     "Abra",
#     "Kadabra",
#     "Simsala",
#     "Traumato",
#     "Hypno",
#     "Mewtu",
#     "Mew",
#     "Psiana",
#     "Icognito",
#     "Woingenau",
#     "Spoink",
#     "Groink",
#     "Palimpalim",
#     "Isso",
#     "Deoxys",
#     "Klingplim",
#     "Selfe",
#     "Vesprit",
#     "Tobutz",
#     "Cresselia",
#     "Pantimos",
#     "Trasla",
#     "Kirlia",
#     "Guardevoir",
#     "Pantimimi",
#     "Natu",
#     "Xatu",
#     "Lugia",
#     "Galagladi",
#     "Celebi",
# ]

# steel = [
#     "Registeel",
#     "Stahlos",
#     "Dialga",
#     "Flunkifer",
#     "Panzaeron",
#     "Stollunior",
#     "Stollrak",
#     "Stollos",
#     "Tanhel",
#     "Metang",
#     "Metagross",
#     "Jirachi",
#     "Bronzel",
#     "Bronzong",
# ]

# dark = [
#     "Nachtara",
#     "Fiffyen",
#     "Magnayen",
#     "Absol",
#     "Darkrai",
#     "Sniebel",
#     "Snibunna",
#     "Hunduster",
#     "Hundemon",
#     "Kramurx",
#     "Kramshef",
#     "Zobiris",
# ]

# water = [
#     "Schiggy",
#     "Schillok",
#     "Turtok",
#     "Enton",
#     "Entoron",
#     "Quapsel",
#     "Quaputzi",
#     "Jurob",
#     "Muschas",
#     "Krabby",
#     "Kingler",
#     "Seeper",
#     "Seemon",
#     "Goldini",
#     "Golking",
#     "Sterndu",
#     "Karpador",
#     "Aquana",
#     "Karnimani",
#     "Tyracroc",
#     "Impergator",
#     "Quaxo",
#     "Remoraid",
#     "Octillery",
#     "Suicune",
#     "Hydropi",
#     "Wailmer",
#     "Wailord",
#     "Krebscorps",
#     "Barschwa",
#     "Milotic",
#     "Perlu",
#     "Aalabyss",
#     "Saganabyss",
#     "Liebiskus",
#     "Kyogre",
#     "Plinfa",
#     "Pliprin",
#     "Bamelin",
#     "Bojelin",
#     "Schalellos",
#     "Finneon",
#     "Lumineon",
#     "Phione",
#     "Manaphy",
#     "Felino",
#     "Morlord",
#     "Moorabbel",
#     "Sumpex",
#     "Schmerbe",
#     "Welsar",
#     "Gastrodon",
#     "Seedraking",
#     "Palkia",
#     "Jugong",
#     "Austos",
#     "Lapras",
#     "Lampi",
#     "Lanturn",
#     "Marill",
#     "Azumarill",
#     "Garados",
#     "Mantax",
#     "Wingull",
#     "Peliper",
#     "Matirps",
#     "Corasonn",
#     "Relicanth",
#     "Tentacha",
#     "Tentoxa",
#     "Baldorfish",
#     "Quappo",
#     "Loturzel",
#     "Lombrero",
#     "Kappalores",
#     "Flegmon",
#     "Lahmus",
#     "Starmie",
#     "Laschoking",
#     "Impoleon",
#     "Karnivanha",
#     "Tohaido",
#     "Krebutack",
# ]
